### ISSUE TITLE
[Enhancement] Names for different roles

### ISSUE THREAD

**Issue by iojforever** [babyboucher/RPNames#3]
**WDYM by "Names for different roles"?**

> You see, there are a huge number of roles in the game. For example, scientists, Chaos Insurgency (now, as many as four different roles of one faction), mobile task force, etc. Not a bad addition would be the ability to set the list for each role individually. For example, a list of names only for Scientists or NTF staff (not necessarily set separately for recruits, sergeants, etc.)

**What the point of this feature?**

> Since this plugin is mainly aimed at role-playing, as the name implies, the ability to set different names for different roles would be a nice innovation. For example, NTF Operators would have call signs (Delta, Foxtrot) and scientists would have real names.

**I dont get it. Can you provide an example?**

> Sure.

```
    # The list of names to be given. (Leave empty for default, if you want to make your own list, look at readme) 
  human_names:
  - example 1
  - example 2
  - example 3
    # Should use names for custom roles?
  custom_roles: false
    # The list of individual names for roles ingame. 
  NtfSergeant:
  - Alpha
  - Beta
  - Gamma
```
